# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7abe69262207d19c149a73cd499199e3dbb861a5fdca251df1e2d241614313302e6a27dfe9ca884ce3c218758d3e2f40eec51609a2c54b7c408b570e60764c5c

test:
  secret_key_base: 3ce27804e6535d0ae77b064848ea36681a1e698108f6d77e72f4bd4b24052d35c1c4a7f0bd5fe28c96224ba92dabca19b1acc9eade7021defb2e6b05b317ff2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
